// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 1240);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1606015028);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{141ecddb-3ef9-4fd6-90fe-f58f58246eb0}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1606015033062");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1606036633062");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1606015031");
user_pref("browser.slowStartup.averageTime", 11477);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200107212822");
user_pref("browser.startup.homepage_override.mstone", "72.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1606015029);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1606015032029");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "0f9c6e5388b046a7a40ae4db857a1bbe");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.1");
user_pref("extensions.lastPlatformVersion", "72.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"0395761b-36cf-45ed-9379-dec5e74b1899\",\"formautofill@mozilla.org\":\"c086b444-e553-4936-8209-a165a540b208\",\"screenshots@mozilla.org\":\"6e1a59e3-38a9-4d27-bfe4-b7ef9c212bf7\",\"webcompat-reporter@mozilla.org\":\"aaeebd30-1fdd-4436-938d-88bc5fe06baa\",\"webcompat@mozilla.org\":\"23151a7c-a524-4116-80b2-43972dc50abc\",\"default-theme@mozilla.org\":\"38adb6d4-352d-4fc8-a69e-2c9257841b6d\",\"google@search.mozilla.org\":\"ca494d17-694b-4c34-9a61-3f0d31768c4a\",\"amazondotcom@search.mozilla.org\":\"ab1dcae9-f75f-4589-94eb-67a7d135b8cf\",\"bing@search.mozilla.org\":\"41c7d91d-b234-419d-8701-cd81d87cbef7\",\"ddg@search.mozilla.org\":\"305f0199-1a69-4340-9e6f-ae432b90ed9c\",\"ebay@search.mozilla.org\":\"44d16509-51ec-43c0-849b-781f94ad89a7\",\"twitter@search.mozilla.org\":\"cd36086e-4416-47b0-bb2f-92fa1c068f01\",\"wikipedia@search.mozilla.org\":\"d50e91fd-029e-4572-a445-deaa0f1d2871\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "53996778-2b50-4b5d-8db5-024c741243de");
user_pref("security.sandbox.plugin.tempDirSuffix", "2b8cd4de-cdf0-424f-b208-d0370c5a3e44");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1606015018);
user_pref("toolkit.telemetry.cachedClientID", "c6b2373f-1de6-482a-b8ba-9a4de60d4acc");
user_pref("toolkit.telemetry.previousBuildID", "20200107212822");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
